name: flip_card
description: A component that provides flip card animation. It could be used for hide and show details of a product.
version: 0.6.0
homepage: https://github.com/fedeoo/flip_card/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 2.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
